apiVersion: v1
kind: Service
metadata:
  name: mportal-postgres
  namespace: mportal
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: mportal-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mportal-postgres
  namespace: mportal
spec:
  serviceName: mportal-postgres
  replicas: 1
  selector:
    matchLabels:
      app: mportal-postgres
  template:
    metadata:
      labels:
        app: mportal-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: mportal-postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 20
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
