apiVersion: v1
kind: Secret
metadata:
  name: mportal-postgres-secret
  namespace: mportal
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: replace-with-strong-password
  POSTGRES_DB: mportal
  CONNECTION_STRING: Host=mportal-postgres;Port=5432;Database=mportal;Username=postgres;Password=replace-with-strong-password
