//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS.WebSystem.Apps.Integration.CommonWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonWS.CommonWSSoap")]
    public interface CommonWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDivisions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[] GetDivisions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDivisions", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[]> GetDivisionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistricts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[] GetDistricts(int divisionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistricts", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[]> GetDistrictsAsync(int divisionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Locale[] GetLocales(int districtID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocales", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Locale[]> GetLocalesAsync(int districtID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Country[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Country[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Country GetCountry(int countryID, string countryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Country> GetCountryAsync(int countryID, string countryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByRegion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Country[] GetCountriesByRegion(int regionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Country[]> GetCountriesByRegionAsync(int regionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocaleGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.LocaleGroup[] GetLocaleGroups(int localeID, int localeGroupID, string localeGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocaleGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.LocaleGroup[]> GetLocaleGroupsAsync(int localeID, int localeGroupID, string localeGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[] GetServiceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[]> GetServiceTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Service[] GetServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServices", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Service[]> GetServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.Service GetService(int serviceID, string serviceCode, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetService", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Service> GetServiceAsync(int serviceID, string serviceCode, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceSchedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule GetServiceSchedule(int serviceScheduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule> GetServiceScheduleAsync(int serviceScheduleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceSchedules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetServiceSchedules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceSchedules", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetServiceSchedulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceScheduleByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetServiceScheduleByDate(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceScheduleByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetServiceScheduleByDateAsync(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceScheduleByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetAllServiceScheduleByDate(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceScheduleByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetAllServiceScheduleByDateAsync(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceSchedulesByMonth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreationDate))]
        WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetServiceSchedulesByMonth(int localeID, int isMainSchedule, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceSchedulesByMonth", ReplyAction="*")]
        System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetServiceSchedulesByMonthAsync(int localeID, int isMainSchedule, int month, int year);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Lookup : CreationDate {
        
        private int lookupIDField;
        
        private int lookupTypeIDField;
        
        private int lookupParentIDField;
        
        private string lookupNameField;
        
        private string descriptionField;
        
        private string configStringField;
        
        private int isParentField;
        
        private int isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LookupID {
            get {
                return this.lookupIDField;
            }
            set {
                this.lookupIDField = value;
                this.RaisePropertyChanged("LookupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LookupTypeID {
            get {
                return this.lookupTypeIDField;
            }
            set {
                this.lookupTypeIDField = value;
                this.RaisePropertyChanged("LookupTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LookupParentID {
            get {
                return this.lookupParentIDField;
            }
            set {
                this.lookupParentIDField = value;
                this.RaisePropertyChanged("LookupParentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LookupName {
            get {
                return this.lookupNameField;
            }
            set {
                this.lookupNameField = value;
                this.RaisePropertyChanged("LookupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ConfigString {
            get {
                return this.configStringField;
            }
            set {
                this.configStringField = value;
                this.RaisePropertyChanged("ConfigString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IsParent {
            get {
                return this.isParentField;
            }
            set {
                this.isParentField = value;
                this.RaisePropertyChanged("IsParent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceSchedule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Service))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocaleGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Country))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Locale))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Lookup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class CreationDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateCreatedField;
        
        private int createdByField;
        
        private System.DateTime dateUpdatedField;
        
        private int updatedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
                this.RaisePropertyChanged("DateUpdated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
                this.RaisePropertyChanged("UpdatedBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceSchedule : CreationDate {
        
        private long serviceScheduleIDField;
        
        private int localeIDField;
        
        private int serviceIDField;
        
        private System.DateTime startServiceDateTimeField;
        
        private System.DateTime endServiceDateTimeField;
        
        private System.DateTime lateDateTimeField;
        
        private string weekNoField;
        
        private int isMainScheduleField;
        
        private long assignedCouncillorField;
        
        private string remarksField;
        
        private int isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ServiceScheduleID {
            get {
                return this.serviceScheduleIDField;
            }
            set {
                this.serviceScheduleIDField = value;
                this.RaisePropertyChanged("ServiceScheduleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
                this.RaisePropertyChanged("LocaleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartServiceDateTime {
            get {
                return this.startServiceDateTimeField;
            }
            set {
                this.startServiceDateTimeField = value;
                this.RaisePropertyChanged("StartServiceDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndServiceDateTime {
            get {
                return this.endServiceDateTimeField;
            }
            set {
                this.endServiceDateTimeField = value;
                this.RaisePropertyChanged("EndServiceDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime LateDateTime {
            get {
                return this.lateDateTimeField;
            }
            set {
                this.lateDateTimeField = value;
                this.RaisePropertyChanged("LateDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string WeekNo {
            get {
                return this.weekNoField;
            }
            set {
                this.weekNoField = value;
                this.RaisePropertyChanged("WeekNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IsMainSchedule {
            get {
                return this.isMainScheduleField;
            }
            set {
                this.isMainScheduleField = value;
                this.RaisePropertyChanged("IsMainSchedule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long AssignedCouncillor {
            get {
                return this.assignedCouncillorField;
            }
            set {
                this.assignedCouncillorField = value;
                this.RaisePropertyChanged("AssignedCouncillor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Service : CreationDate {
        
        private int serviceIDField;
        
        private int serviceTypeIDField;
        
        private int scheduleTypeIDField;
        
        private string serviceCodeField;
        
        private string descriptionField;
        
        private int isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ServiceTypeID {
            get {
                return this.serviceTypeIDField;
            }
            set {
                this.serviceTypeIDField = value;
                this.RaisePropertyChanged("ServiceTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ScheduleTypeID {
            get {
                return this.scheduleTypeIDField;
            }
            set {
                this.scheduleTypeIDField = value;
                this.RaisePropertyChanged("ScheduleTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LocaleGroup : CreationDate {
        
        private int localeGroupIDField;
        
        private int localeIDField;
        
        private string localeGroupNameField;
        
        private string colorCodesField;
        
        private int isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LocaleGroupID {
            get {
                return this.localeGroupIDField;
            }
            set {
                this.localeGroupIDField = value;
                this.RaisePropertyChanged("LocaleGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
                this.RaisePropertyChanged("LocaleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocaleGroupName {
            get {
                return this.localeGroupNameField;
            }
            set {
                this.localeGroupNameField = value;
                this.RaisePropertyChanged("LocaleGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ColorCodes {
            get {
                return this.colorCodesField;
            }
            set {
                this.colorCodesField = value;
                this.RaisePropertyChanged("ColorCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Country : CreationDate {
        
        private int countryIDField;
        
        private int regionIDField;
        
        private int capitalIDField;
        
        private int divisionIDField;
        
        private string countryNameField;
        
        private string countryCodeField;
        
        private int isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
                this.RaisePropertyChanged("CountryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RegionID {
            get {
                return this.regionIDField;
            }
            set {
                this.regionIDField = value;
                this.RaisePropertyChanged("RegionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CapitalID {
            get {
                return this.capitalIDField;
            }
            set {
                this.capitalIDField = value;
                this.RaisePropertyChanged("CapitalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DivisionID {
            get {
                return this.divisionIDField;
            }
            set {
                this.divisionIDField = value;
                this.RaisePropertyChanged("DivisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
                this.RaisePropertyChanged("CountryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Locale : CreationDate {
        
        private int localeIDField;
        
        private int divisionIDField;
        
        private int districtIDField;
        
        private int localeTypeIDField;
        
        private string localeNameField;
        
        private string localeCodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private int cityIDField;
        
        private int stateIDField;
        
        private int countryIDField;
        
        private string postalCodeField;
        
        private string phoneField;
        
        private string emailField;
        
        private System.DateTime dateFoundedField;
        
        private int isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
                this.RaisePropertyChanged("LocaleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DivisionID {
            get {
                return this.divisionIDField;
            }
            set {
                this.divisionIDField = value;
                this.RaisePropertyChanged("DivisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DistrictID {
            get {
                return this.districtIDField;
            }
            set {
                this.districtIDField = value;
                this.RaisePropertyChanged("DistrictID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int LocaleTypeID {
            get {
                return this.localeTypeIDField;
            }
            set {
                this.localeTypeIDField = value;
                this.RaisePropertyChanged("LocaleTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocaleName {
            get {
                return this.localeNameField;
            }
            set {
                this.localeNameField = value;
                this.RaisePropertyChanged("LocaleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LocaleCode {
            get {
                return this.localeCodeField;
            }
            set {
                this.localeCodeField = value;
                this.RaisePropertyChanged("LocaleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int CityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
                this.RaisePropertyChanged("CityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int StateID {
            get {
                return this.stateIDField;
            }
            set {
                this.stateIDField = value;
                this.RaisePropertyChanged("StateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
                this.RaisePropertyChanged("CountryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime DateFounded {
            get {
                return this.dateFoundedField;
            }
            set {
                this.dateFoundedField = value;
                this.RaisePropertyChanged("DateFounded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommonWSSoapChannel : WCMS.WebSystem.Apps.Integration.CommonWS.CommonWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonWSSoapClient : System.ServiceModel.ClientBase<WCMS.WebSystem.Apps.Integration.CommonWS.CommonWSSoap>, WCMS.WebSystem.Apps.Integration.CommonWS.CommonWSSoap {
        
        public CommonWSSoapClient() {
        }
        
        public CommonWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[] GetDivisions() {
            return base.Channel.GetDivisions();
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[]> GetDivisionsAsync() {
            return base.Channel.GetDivisionsAsync();
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[] GetDistricts(int divisionID) {
            return base.Channel.GetDistricts(divisionID);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[]> GetDistrictsAsync(int divisionID) {
            return base.Channel.GetDistrictsAsync(divisionID);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Locale[] GetLocales(int districtID) {
            return base.Channel.GetLocales(districtID);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Locale[]> GetLocalesAsync(int districtID) {
            return base.Channel.GetLocalesAsync(districtID);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Country[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Country[]> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Country GetCountry(int countryID, string countryName) {
            return base.Channel.GetCountry(countryID, countryName);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Country> GetCountryAsync(int countryID, string countryName) {
            return base.Channel.GetCountryAsync(countryID, countryName);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Country[] GetCountriesByRegion(int regionID) {
            return base.Channel.GetCountriesByRegion(regionID);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Country[]> GetCountriesByRegionAsync(int regionID) {
            return base.Channel.GetCountriesByRegionAsync(regionID);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.LocaleGroup[] GetLocaleGroups(int localeID, int localeGroupID, string localeGroupName) {
            return base.Channel.GetLocaleGroups(localeID, localeGroupID, localeGroupName);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.LocaleGroup[]> GetLocaleGroupsAsync(int localeID, int localeGroupID, string localeGroupName) {
            return base.Channel.GetLocaleGroupsAsync(localeID, localeGroupID, localeGroupName);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[] GetServiceTypes() {
            return base.Channel.GetServiceTypes();
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Lookup[]> GetServiceTypesAsync() {
            return base.Channel.GetServiceTypesAsync();
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Service[] GetServices() {
            return base.Channel.GetServices();
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Service[]> GetServicesAsync() {
            return base.Channel.GetServicesAsync();
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.Service GetService(int serviceID, string serviceCode, string description) {
            return base.Channel.GetService(serviceID, serviceCode, description);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.Service> GetServiceAsync(int serviceID, string serviceCode, string description) {
            return base.Channel.GetServiceAsync(serviceID, serviceCode, description);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule GetServiceSchedule(int serviceScheduleID) {
            return base.Channel.GetServiceSchedule(serviceScheduleID);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule> GetServiceScheduleAsync(int serviceScheduleID) {
            return base.Channel.GetServiceScheduleAsync(serviceScheduleID);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetServiceSchedules() {
            return base.Channel.GetServiceSchedules();
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetServiceSchedulesAsync() {
            return base.Channel.GetServiceSchedulesAsync();
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetServiceScheduleByDate(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate) {
            return base.Channel.GetServiceScheduleByDate(localeID, serviceStartDate, serviceEndDate);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetServiceScheduleByDateAsync(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate) {
            return base.Channel.GetServiceScheduleByDateAsync(localeID, serviceStartDate, serviceEndDate);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetAllServiceScheduleByDate(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate) {
            return base.Channel.GetAllServiceScheduleByDate(localeID, serviceStartDate, serviceEndDate);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetAllServiceScheduleByDateAsync(int localeID, System.DateTime serviceStartDate, System.DateTime serviceEndDate) {
            return base.Channel.GetAllServiceScheduleByDateAsync(localeID, serviceStartDate, serviceEndDate);
        }
        
        public WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[] GetServiceSchedulesByMonth(int localeID, int isMainSchedule, int month, int year) {
            return base.Channel.GetServiceSchedulesByMonth(localeID, isMainSchedule, month, year);
        }
        
        public System.Threading.Tasks.Task<WCMS.WebSystem.Apps.Integration.CommonWS.ServiceSchedule[]> GetServiceSchedulesByMonthAsync(int localeID, int isMainSchedule, int month, int year) {
            return base.Channel.GetServiceSchedulesByMonthAsync(localeID, isMainSchedule, month, year);
        }
    }
}
