//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS.WebSystem.WebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServices.IDataSync")]
    public interface IDataSync {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/DoWork", ReplyAction="http://tempuri.org/IDataSync/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/GetObject", ReplyAction="http://tempuri.org/IDataSync/GetObjectResponse")]
        WCMS.Framework.WebUser GetObject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/GetObjectList", ReplyAction="http://tempuri.org/IDataSync/GetObjectListResponse")]
        WCMS.Framework.WebUser[] GetObjectList(int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/GetUserComplete", ReplyAction="http://tempuri.org/IDataSync/GetUserCompleteResponse")]
        WCMS.Framework.WebUserContainer GetUserComplete(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/SetUserComplete", ReplyAction="http://tempuri.org/IDataSync/SetUserCompleteResponse")]
        void SetUserComplete(WCMS.Framework.WebUserContainer container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/GetFiles", ReplyAction="http://tempuri.org/IDataSync/GetFilesResponse")]
        WCMS.Framework.Net.FileSyncInfo[] GetFiles(string relativePath, bool recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSync/GetBindings", ReplyAction="http://tempuri.org/IDataSync/GetBindingsResponse")]
        WCMS.Framework.Core.WebSiteIdentity[] GetBindings();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataSyncChannel : WCMS.WebSystem.WebServices.IDataSync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataSyncClient : System.ServiceModel.ClientBase<WCMS.WebSystem.WebServices.IDataSync>, WCMS.WebSystem.WebServices.IDataSync {
        
        public DataSyncClient() {
        }
        
        public DataSyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataSyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataSyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataSyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public WCMS.Framework.WebUser GetObject() {
            return base.Channel.GetObject();
        }
        
        public WCMS.Framework.WebUser[] GetObjectList(int objectId) {
            return base.Channel.GetObjectList(objectId);
        }
        
        public WCMS.Framework.WebUserContainer GetUserComplete(int userId) {
            return base.Channel.GetUserComplete(userId);
        }
        
        public void SetUserComplete(WCMS.Framework.WebUserContainer container) {
            base.Channel.SetUserComplete(container);
        }
        
        public WCMS.Framework.Net.FileSyncInfo[] GetFiles(string relativePath, bool recursive) {
            return base.Channel.GetFiles(relativePath, recursive);
        }
        
        public WCMS.Framework.Core.WebSiteIdentity[] GetBindings() {
            return base.Channel.GetBindings();
        }
    }
}
