SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EventCalendar]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[EventCalendar](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](250) COLLATE Latin1_General_CI_AI NOT NULL,
	[SiteId] [int] NOT NULL,
 CONSTRAINT [PK_EventCalendar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__EventCalendar]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EventCalendar] ADD  CONSTRAINT [DF__EventCalendar]  DEFAULT ((-1)) FOR [SiteId]
END

GO
