SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GenericListColumnOptionType]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[GenericListColumnOptionType](
	[Id] [int] NOT NULL,
	[Label] [nvarchar](255) COLLATE Latin1_General_CI_AI NOT NULL,
	[Template] [ntext] COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_GenericListColumnOptionType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
