SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RemoteDataMap]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RemoteDataMap](
	[Id] [int] NOT NULL,
	[InstanceId] [int] NOT NULL,
	[ObjectId] [int] NOT NULL,
	[LocalId] [int] NOT NULL,
	[RemoteId] [int] NOT NULL,
 CONSTRAINT [PK_RemoteDataMap] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
