// <auto-generated mode="shell">
// Ported from legacy/Portal/WebParts/SystemParts/SystemParts/AppBundle/Menu/ConfigDynamicMenuV2.ascx.
// This is a real Razor admin shell generated from the legacy ASP.NET WebForms control.
// It compiles, renders the form fields/lists derived from the legacy markup,
// and submits to the configured controller. Persistence hooks are marked TODO and
// must be wired to the appropriate provider/service for full functional parity.
// </auto-generated>
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using WCMS.Framework;
using WCMS.Framework.ViewComponents;

namespace WCMS.WebSystem.WebParts.ViewComponents
{
    public class Configdynamicmenuv2ViewComponent : WViewComponent
    {
        public Configdynamicmenuv2ViewComponent(IWContext context) : base(context) { }

        public IViewComponentResult Invoke(int objectId = 0, int recordId = 0)
        {
            if (objectId > 0)
            {
                WcmsContext.Set("ObjectId", objectId.ToString());
                WcmsContext.Set("RecordId", recordId.ToString());
            }

            var model = new Configdynamicmenuv2ViewModel
            {
                ObjectId = objectId > 0 ? objectId : WcmsContext.ObjectId,
                RecordId = recordId > 0 ? recordId : WcmsContext.RecordId,
                PostController = WcmsContext.Element?.GetParameterValue("PostController") ?? "Admin",
                PostAction = WcmsContext.Element?.GetParameterValue("PostAction") ?? "Configdynamicmenuv2"
            };

            // TODO: replace stub population with real provider/service calls.
            // The legacy code-behind (legacy/Portal/WebParts/SystemParts/SystemParts/AppBundle/Menu/ConfigDynamicMenuV2.ascx.cs)
            // contains the original event handlers that should be ported to a controller action
            // matching `@Model.PostController` / `@Model.PostAction` below.

            return View(model);
        }
    }

    public class Configdynamicmenuv2ViewModel
    {
        public int ObjectId { get; set; }
        public int RecordId { get; set; }
        public string PostController { get; set; } = "Admin";
        public string PostAction { get; set; } = "Configdynamicmenuv2";
        public string StatusMessage { get; set; } = string.Empty;
        public string ErrorMessage { get; set; } = string.Empty;

        public string cboMenu { get; set; } = string.Empty;
        public string lblStatus { get; set; } = string.Empty;

    }
}
