// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WCMS.WebSystem.Apps.Integration.Data;

#nullable disable

namespace WCMS.WebSystem.Apps.Integration.Data.Migrations.SqlServer.IntegrationDb
{
    [DbContext(typeof(IntegrationDbContext))]
    partial class IntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.GenericRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Airline")
                        .HasColumnType("text");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("FlightNo")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PlaceType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MCCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Entry")
                        .HasColumnType("text");

                    b.Property<string>("Interpreter")
                        .HasColumnType("text");

                    b.Property<string>("Lyricist")
                        .HasColumnType("text");

                    b.Property<string>("Lyrics")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhotoFile")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl2")
                        .HasColumnType("text");

                    b.Property<int>("WinnerRank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MCCandidates", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MCComposer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("integer");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Entry")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("PhotoFile")
                        .HasColumnType("text");

                    b.Property<string>("Work")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MCComposers", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MCInterpreterScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Interpretation")
                        .HasColumnType("integer");

                    b.Property<int>("JudgeId")
                        .HasColumnType("integer");

                    b.Property<int>("OverallImpact")
                        .HasColumnType("integer");

                    b.Property<int>("StagePresence")
                        .HasColumnType("integer");

                    b.Property<int>("VoiceQuality")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MCInterpreterScores", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MCSongScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JudgeId")
                        .HasColumnType("integer");

                    b.Property<int>("LyricsMessage")
                        .HasColumnType("integer");

                    b.Property<int>("Musicality")
                        .HasColumnType("integer");

                    b.Property<int>("OverallImpact")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MCSongScores", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MCVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateVoted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<int>("Spam")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MCVotes", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MemberLink", b =>
                {
                    b.Property<int>("MemberLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberLinkId"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<int>("Approved")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalIdNo")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressLine2")
                        .HasColumnType("text");

                    b.Property<int>("HomeAddressStateCode")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAddressZipCode")
                        .HasColumnType("text");

                    b.Property<string>("HomePhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<int>("LocaleCountryCode")
                        .HasColumnType("integer")
                        .HasColumnName("HomeAddressCountryCode");

                    b.Property<int>("LocaleId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<int>("Private")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkAddressCountryCode")
                        .HasColumnType("integer");

                    b.Property<string>("WorkAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("WorkAddressLine2")
                        .HasColumnType("text");

                    b.Property<int>("WorkAddressStateCode")
                        .HasColumnType("integer");

                    b.Property<string>("WorkAddressZipCode")
                        .HasColumnType("text");

                    b.Property<string>("WorkDesignation")
                        .HasColumnType("text");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("text");

                    b.HasKey("MemberLinkId");

                    b.ToTable("MemberLinks", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.MemberVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .HasColumnType("text");

                    b.Property<string>("ActualReport")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactNo")
                        .HasColumnType("text");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateVisited")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int>("TimesVisited")
                        .HasColumnType("integer");

                    b.Property<int>("VisitedUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ODKVisits", (string)null);
                });

            modelBuilder.Entity("WCMS.WebSystem.Apps.Integration.Sportsfest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CountryCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupColor")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ShirtSize")
                        .HasColumnType("text");

                    b.Property<string>("Sports")
                        .HasColumnType("text");

                    b.Property<string>("Suggestion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sportsfests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
