CREATE TABLE [dbo].[MemberLink] (
    [MemberLinkId]           INT             NOT NULL,
    [UserId]                 INT             NOT NULL,
    [MemberId]               INT             CONSTRAINT [DF_MemberLink_MemberId] DEFAULT ((-1)) NOT NULL,
    [ExternalIdNo]             NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_ExternalIdNo] DEFAULT ('') NOT NULL,
    [HomeAddressLine1]       NVARCHAR (250)  COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_HomeAddressLine1] DEFAULT ('') NOT NULL,
    [HomeAddressStateCode]   INT             CONSTRAINT [DF_MemberLink_HomeAddressStateCode] DEFAULT ((-1)) NOT NULL,
    [HomeAddressCountryCode] INT             CONSTRAINT [DF_MemberLink_HomeAddressCountryCode] DEFAULT ((-1)) NOT NULL,
    [HomeAddressZipCode]     NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_HomeAddressZipCode] DEFAULT ('') NOT NULL,
    [MobileNumber]           NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_MobileNumber] DEFAULT ('') NOT NULL,
    [HomePhone]              NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_HomePhone] DEFAULT ('') NOT NULL,
    [WorkAddressLine1]       NVARCHAR (250)  COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_WorkAddressLine1] DEFAULT ('') NOT NULL,
    [WorkAddressStateCode]   INT             CONSTRAINT [DF_MemberLink_WorkAddressStateCode] DEFAULT ((-1)) NOT NULL,
    [WorkAddressCountryCode] INT             CONSTRAINT [DF_MemberLink_WorkAddressCountryCode] DEFAULT ((-1)) NOT NULL,
    [WorkAddressZipCode]     NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_WorkAddressZipCode] DEFAULT ('') NOT NULL,
    [WorkDesignation]        NVARCHAR (250)  COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_WorkDesignation] DEFAULT ('') NOT NULL,
    [WorkPhone]              NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_WorkPhone] DEFAULT ('') NOT NULL,
    [Nickname]               NVARCHAR (50)   COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_Nickname] DEFAULT ('') NOT NULL,
    [LastUpdate]             DATETIME        CONSTRAINT [DF_MemberLink_LastUpdate] DEFAULT (getdate()) NOT NULL,
    [PhotoPath]              NVARCHAR (500)  COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_PhotoPath] DEFAULT ('') NOT NULL,
    [MembershipDate]            DATETIME        CONSTRAINT [DF_MemberLink_MembershipDate] DEFAULT (getdate()) NOT NULL,
    [Approved]               INT             CONSTRAINT [DF_MemberLink_Approved] DEFAULT ((0)) NOT NULL,
    [Locale]                 NVARCHAR (2000) COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_Locale] DEFAULT ('') NOT NULL,
    [HomeAddressLine2]       NVARCHAR (250)  COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_HomeAddressLine11] DEFAULT ('') NOT NULL,
    [WorkAddressLine2]       NVARCHAR (250)  COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_HomeAddressLine11_1] DEFAULT ('') NOT NULL,
    [Private]                INT             CONSTRAINT [DF_MemberLink_Private] DEFAULT ((0)) NOT NULL,
    [AdditionalInfo]         NVARCHAR (4000) COLLATE Latin1_General_CI_AI CONSTRAINT [DF_MemberLink_AdditionalInformation] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_MemberLink] PRIMARY KEY CLUSTERED ([MemberLinkId] ASC)
);

